POST /v1/create_user HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Length: 108

{
    "username":"alice2",
    "password":"secret",
    "full_name":"Agor",
    "email":"alice2@mail.com"
}